# Solutions

1. [NumPy][1]
2. [Pandas][2]
3. [Seaborn][3]
4. [Scikit-Learn][4]

[1]: #1.-NumPy
[2]: #2.-Pandas
[3]: #3.-Seaborn
[4]: #4.-Scikit-Learn

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
%matplotlib inline

# 1. NumPy

### Problem 1
<span style="color:green">Create an array with 5 rows and 8 columns of random dice rolls. Assign it to variable `arr` and output it to the screen. Set the random number generation seed to 1 before creation.</span>

In [28]:
np.random.seed(1)
arr = np.random.randint(1, 7, (5, 8))
arr

array([[6, 4, 5, 1, 2, 4, 6, 1],
       [1, 2, 5, 6, 5, 2, 3, 5],
       [6, 3, 5, 4, 5, 3, 5, 6],
       [3, 5, 2, 2, 1, 6, 2, 2],
       [6, 2, 2, 1, 5, 2, 1, 1]])

### Problem 2
<span style="color:green">Select single elements of `arr` multiple times.</span>

In [29]:
arr[1, 3]

6

In [30]:
arr[-1, -2]

1

In [31]:
arr[4, 4]

5

### Problem 3
<span style="color:green">Select many subsets of elements of `arr` using slice notation.</span>

In [32]:
arr[2:4, 3:5]

array([[4, 5],
       [2, 1]])

In [33]:
# this selects all of the columns
arr[2:4]

array([[6, 3, 5, 4, 5, 3, 5, 6],
       [3, 5, 2, 2, 1, 6, 2, 2]])

In [34]:
# Select all of the rows
arr[:, 2]

array([5, 5, 5, 2, 2])

### Problem 4
<span style="color:green">Practice using the basic vectorized arithmetic operations.</span>

In [35]:
arr / 2

array([[3. , 2. , 2.5, 0.5, 1. , 2. , 3. , 0.5],
       [0.5, 1. , 2.5, 3. , 2.5, 1. , 1.5, 2.5],
       [3. , 1.5, 2.5, 2. , 2.5, 1.5, 2.5, 3. ],
       [1.5, 2.5, 1. , 1. , 0.5, 3. , 1. , 1. ],
       [3. , 1. , 1. , 0.5, 2.5, 1. , 0.5, 0.5]])

In [36]:
# floor division
arr // 2

array([[3, 2, 2, 0, 1, 2, 3, 0],
       [0, 1, 2, 3, 2, 1, 1, 2],
       [3, 1, 2, 2, 2, 1, 2, 3],
       [1, 2, 1, 1, 0, 3, 1, 1],
       [3, 1, 1, 0, 2, 1, 0, 0]])

In [37]:
# raise to a power
arr ** 2

array([[36, 16, 25,  1,  4, 16, 36,  1],
       [ 1,  4, 25, 36, 25,  4,  9, 25],
       [36,  9, 25, 16, 25,  9, 25, 36],
       [ 9, 25,  4,  4,  1, 36,  4,  4],
       [36,  4,  4,  1, 25,  4,  1,  1]])

In [38]:
# modulus - get remainder
arr % 3

array([[0, 1, 2, 1, 2, 1, 0, 1],
       [1, 2, 2, 0, 2, 2, 0, 2],
       [0, 0, 2, 1, 2, 0, 2, 0],
       [0, 2, 2, 2, 1, 0, 2, 2],
       [0, 2, 2, 1, 2, 2, 1, 1]])

### Problem 5
<span style="color:green">Practice calling many of the methods. Use the tab completion help to find them. Change the direction of operation with the **`axis`** parameter.</span>

In [39]:
arr.std()

1.8159019797334879

In [40]:
arr.argmax()

0

In [41]:
arr.argmax(axis=0)

array([0, 3, 0, 1, 1, 3, 0, 2])

In [42]:
arr.cumsum()

array([  6,  10,  15,  16,  18,  22,  28,  29,  30,  32,  37,  43,  48,
        50,  53,  58,  64,  67,  72,  76,  81,  84,  89,  95,  98, 103,
       105, 107, 108, 114, 116, 118, 124, 126, 128, 129, 134, 136, 137,
       138])

In [44]:
# across
arr.cumsum(axis=1)

array([[ 6, 10, 15, 16, 18, 22, 28, 29],
       [ 1,  3,  8, 14, 19, 21, 24, 29],
       [ 6,  9, 14, 18, 23, 26, 31, 37],
       [ 3,  8, 10, 12, 13, 19, 21, 23],
       [ 6,  8, 10, 11, 16, 18, 19, 20]])

In [45]:
arr.repeat(3)

array([6, 6, 6, 4, 4, 4, 5, 5, 5, 1, 1, 1, 2, 2, 2, 4, 4, 4, 6, 6, 6, 1,
       1, 1, 1, 1, 1, 2, 2, 2, 5, 5, 5, 6, 6, 6, 5, 5, 5, 2, 2, 2, 3, 3,
       3, 5, 5, 5, 6, 6, 6, 3, 3, 3, 5, 5, 5, 4, 4, 4, 5, 5, 5, 3, 3, 3,
       5, 5, 5, 6, 6, 6, 3, 3, 3, 5, 5, 5, 2, 2, 2, 2, 2, 2, 1, 1, 1, 6,
       6, 6, 2, 2, 2, 2, 2, 2, 6, 6, 6, 2, 2, 2, 2, 2, 2, 1, 1, 1, 5, 5,
       5, 2, 2, 2, 1, 1, 1, 1, 1, 1])

### Problem 6
<span style="color:green">Practice calling many NumPy functions. Find them by using tab completion with **`np.`**.  Use the functions that have an array as their first parameter.</span>

In [48]:
np.arctan(arr)

array([[1.40564765, 1.32581766, 1.37340077, 0.78539816, 1.10714872,
        1.32581766, 1.40564765, 0.78539816],
       [0.78539816, 1.10714872, 1.37340077, 1.40564765, 1.37340077,
        1.10714872, 1.24904577, 1.37340077],
       [1.40564765, 1.24904577, 1.37340077, 1.32581766, 1.37340077,
        1.24904577, 1.37340077, 1.40564765],
       [1.24904577, 1.37340077, 1.10714872, 1.10714872, 0.78539816,
        1.40564765, 1.10714872, 1.10714872],
       [1.40564765, 1.10714872, 1.10714872, 0.78539816, 1.37340077,
        1.10714872, 0.78539816, 0.78539816]])

In [49]:
np.diag(arr)

array([6, 2, 5, 2, 5])

In [56]:
# Get the 30th percentile of each column
np.percentile(arr, q=.3, axis=0)

array([1.024, 2.   , 2.   , 1.   , 1.012, 2.   , 1.012, 1.   ])

### Problem 7
<span style="color:green">Which column has the highest average roll?</span>

In [58]:
# third column
arr.mean(axis=1)

array([3.625, 3.625, 4.625, 2.875, 2.5  ])

In [59]:
# automate with numpy
arr.mean(axis=1).argmax()

2

### Problem 8
<span style="color:green">Find the average roll for all rolls. Then find the average roll for each row. Which rows have an average that is higher than the average for all rolls?

In [60]:
overall_avg = arr.mean()
overall_avg

3.45

In [61]:
row_avg = arr.mean(axis=1)
row_avg

array([3.625, 3.625, 4.625, 2.875, 2.5  ])

In [62]:
row_avg > overall_avg

array([ True,  True,  True, False, False])

In [64]:
# get the location of rows that are True
np.where(row_avg > overall_avg)

(array([0, 1, 2]),)

# 2. Pandas

# 3. Seaborn

# 4. Scikit-Learn